--1)What is the total sales revenue for each product category in each city?

SELECT ST.STORE_CITY,
	P.PRODUCT_CATEGORY,
	SUM(S.UNITS * P.PRODUCT_PRICE) AS TOTAL_REVENUE
FROM SALES S
INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
GROUP BY ST.STORE_CITY,P.PRODUCT_CATEGORY;

--2)Which store has the highest profit in a day?

SELECT S.STORE_ID,
	ST.STORE_NAME,
	DATE_TRUNC('day',S.DATE) AS DAY,
	SUM(S.UNITS * (P.PRODUCT_PRICE - P.PRODUCT_COST)) AS DAILY_PROFIT
FROM SALES S
INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
GROUP BY S.STORE_ID,
	ST.STORE_NAME,
	DATE_TRUNC('day',S.DATE)
ORDER BY DAILY_PROFIT DESC
LIMIT 1

--3)What is the total stock on hand for each product category across all stores?

SELECT P.PRODUCT_CATEGORY,
	SUM(I.STOCK_ON_HAND) AS TOTAL_STOCK
FROM INVENTORY I
INNER JOIN PRODUCTS P ON I.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CATEGORY
ORDER BY TOTAL_STOCK DESC;

--4) What are the product categories that make the most profit in total for each city?

WITH PRODUCTPROFITS AS
	(SELECT ST.STORE_CITY,
			P.PRODUCT_ID,
			P.PRODUCT_CATEGORY,
			SUM(S.UNITS * (P.PRODUCT_PRICE - P.PRODUCT_COST)) AS TOTAL_PROFIT
		FROM SALES S
		INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
		INNER JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
		GROUP BY ST.STORE_CITY,
			P.PRODUCT_ID,
			P.PRODUCT_CATEGORY),
	MAXPRODUCTPROFIT AS
	(SELECT STORE_CITY,
			MAX(TOTAL_PROFIT) AS MAX_PROFIT
		FROM PRODUCTPROFITS
		GROUP BY STORE_CITY)
SELECT PP.STORE_CITY,
	PP.PRODUCT_CATEGORY,
	PP.TOTAL_PROFIT
FROM PRODUCTPROFITS PP
INNER JOIN MAXPRODUCTPROFIT MPP ON PP.STORE_CITY = MPP.STORE_CITY
AND PP.TOTAL_PROFIT = MPP.MAX_PROFIT
ORDER BY PP.STORE_CITY;


--5)For each store, what is the total revenue generated in the first quarter of the year (January to March)?

SELECT ST.STORE_NAME,
	SUM(S.UNITS * P.PRODUCT_PRICE) AS TOTAL_REVENUE_1ST_QUARTER
FROM SALES S
INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
WHERE EXTRACT(MONTH	FROM S.DATE) BETWEEN 1 AND 3
GROUP BY ST.STORE_NAME;

--6) What is the top selling product of each store  ?

WITH TOPSELLINGPRODUCTS AS
	(SELECT S.STORE_ID,
			P.PRODUCT_ID,
			P.PRODUCT_NAME,
			SUM(S.UNITS) AS TOTAL_SALES,
			ROW_NUMBER() OVER (PARTITION BY S.STORE_ID ORDER BY SUM(S.UNITS) DESC) AS RN
		FROM SALES S
		INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
		GROUP BY S.STORE_ID,
			P.PRODUCT_ID,
			P.PRODUCT_NAME)
SELECT ST.STORE_NAME,
	TSP.PRODUCT_NAME,
	TSP.TOTAL_SALES
FROM TOPSELLINGPRODUCTS TSP
INNER JOIN STORES ST ON TSP.STORE_ID = ST.STORE_ID
WHERE TSP.RN = 1
ORDER BY TOTAL_SALES DESC;


--7)For each product category, what is the total stock on hand across all AND what percentage of the total stock are these?

WITH TOTALSTOCKPERCATEGORY AS
	(SELECT P.PRODUCT_CATEGORY,
			SUM(I.STOCK_ON_HAND) AS TOTAL_STOCK_PER_CATEGORY
		FROM INVENTORY I
		INNER JOIN PRODUCTS P ON I.PRODUCT_ID = P.PRODUCT_ID
		GROUP BY P.PRODUCT_CATEGORY)
SELECT T.PRODUCT_CATEGORY,
	T.TOTAL_STOCK_PER_CATEGORY AS TOTAL_STOCK,
	(T.TOTAL_STOCK_PER_CATEGORY * 100) / TOTAL_STOCK.TOTAL_STOCK AS PERCENTAGE_OF_TOTAL_STOCK
FROM TOTALSTOCKPERCATEGORY T,

	(SELECT SUM(STOCK_ON_HAND) AS TOTAL_STOCK
		FROM INVENTORY) AS TOTAL_STOCK;

--8)What are the top 10 products have been sold most?

SELECT P.PRODUCT_NAME,
	   COUNT(*) AS TOTAL_SALE
FROM SALES S
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SALE DESC
LIMIT 10;

--9) Find the most profitable product for each store.

WITH PRODUCTPROFITS AS
	(SELECT S.STORE_ID,
			P.PRODUCT_ID,
			P.PRODUCT_NAME,
			SUM(S.UNITS * (P.PRODUCT_PRICE - P.PRODUCT_COST)) AS TOTAL_PROFIT,
			ROW_NUMBER() OVER (PARTITION BY S.STORE_ID ORDER BY SUM(S.UNITS * (P.PRODUCT_PRICE - P.PRODUCT_COST)) DESC) AS RN
		FROM SALES S
		INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
		GROUP BY S.STORE_ID,
			P.PRODUCT_ID,
			P.PRODUCT_NAME)
SELECT ST.STORE_NAME,
	PP.PRODUCT_NAME,
	PP.TOTAL_PROFIT
FROM PRODUCTPROFITS PP
INNER JOIN STORES ST ON PP.STORE_ID = ST.STORE_ID
WHERE PP.RN = 1;

--10) How much is the average profit margin of each store since their opening ?

WITH STORESALES AS
	(SELECT S.STORE_ID,
			ST.STORE_NAME,
			SUM(S.UNITS * (P.PRODUCT_PRICE - P.PRODUCT_COST)) AS TOTAL_PROFIT,
			SUM(S.UNITS * P.PRODUCT_PRICE) AS TOTAL_REVENUE
		FROM SALES S
		INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
		INNER JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
		GROUP BY S.STORE_ID,
			ST.STORE_NAME),
	STOREPROFITMARGINS AS
	(SELECT STORE_ID,
			STORE_NAME,
			TOTAL_PROFIT,
			TOTAL_REVENUE,
			CASE WHEN TOTAL_REVENUE = 0 THEN 0
				ELSE ROUND((TOTAL_PROFIT / TOTAL_REVENUE) * 100,2)
			END AS PROFIT_MARGIN
		FROM STORESALES)
SELECT STORE_NAME,
	PROFIT_MARGIN
FROM STOREPROFITMARGINS
ORDER BY PROFIT_MARGIN DESC;

--11) Show stores with the highest profit margins of each month.

WITH MONTHLYSTORESALES AS
	(SELECT S.STORE_ID,
			ST.STORE_NAME,
			TO_CHAR(DATE_TRUNC('month',	S.DATE),'YYYY-MM') AS MONTH,
			SUM(S.UNITS * (P.PRODUCT_PRICE - P.PRODUCT_COST)) AS MONTHLY_PROFIT,
			SUM(S.UNITS * P.PRODUCT_PRICE) AS MONTHLY_REVENUE
		FROM SALES S
		INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
		INNER JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
		GROUP BY S.STORE_ID,ST.STORE_NAME,TO_CHAR(DATE_TRUNC('month',S.DATE),'YYYY-MM')),
	MONTHLYPROFITMARGINS AS
	(SELECT STORE_ID,
			STORE_NAME,
			MONTH,
			CASE WHEN MONTHLY_REVENUE = 0 THEN 0
				ELSE ROUND((MONTHLY_PROFIT / MONTHLY_REVENUE) * 100,2)
			END AS MONTHLY_PROFIT_MARGIN,
			ROW_NUMBER() OVER (PARTITION BY MONTH ORDER BY (MONTHLY_PROFIT / MONTHLY_REVENUE) DESC) AS RANK
		FROM MONTHLYSTORESALES)
SELECT STORE_NAME,
	MONTH,
	MONTHLY_PROFIT_MARGIN
FROM MONTHLYPROFITMARGINS
WHERE RANK = 1
ORDER BY MONTH;

--12) Which city or cities have the most stores ?

WITH STORECOUNTS AS
	(SELECT STORE_CITY,
			COUNT(*) AS STORE_COUNT
		FROM STORES
		GROUP BY STORE_CITY),
	MAXSTORECOUNT AS
	(SELECT MAX(STORE_COUNT) AS MAX_COUNT
		FROM STORECOUNTS)
SELECT STORE_CITY,
	STORE_COUNT
FROM STORECOUNTS
WHERE STORE_COUNT =
		(SELECT MAX_COUNT
			FROM MAXSTORECOUNT)
ORDER BY STORE_CITY;

--if we simple do a 'count' and 'limit 1' query it would have choose one of city instead of the other cities which may have the same amount

--13) Which categories have the most revenue?
	
SELECT P.PRODUCT_CATEGORY,
	   SUM(S.UNITS * P.PRODUCT_PRICE) AS TOTAL_REVENUE
FROM SALES S
INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CATEGORY
ORDER BY TOTAL_REVENUE DESC;

--14) Which is the most profitable month ?

SELECT DATE_TRUNC('month',S.DATE) AS MONTH,
	SUM(S.UNITS * (P.PRODUCT_PRICE - P.PRODUCT_COST)) AS TOTAL_PROFIT
FROM SALES S
INNER JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY DATE_TRUNC('month',S.DATE)
ORDER BY TOTAL_PROFIT DESC
LIMIT 1;

--15) What is the difference of product cost and price between highest product price and lowest product price?
SELECT
	(SELECT MAX(PRODUCT_PRICE) FROM PRODUCTS)-(SELECT MIN(PRODUCT_PRICE) FROM PRODUCTS) AS PRICE_DIFFERENCE,
	(SELECT PRODUCT_COST FROM PRODUCTS WHERE PRODUCT_PRICE =
				(SELECT MAX(PRODUCT_PRICE)FROM PRODUCTS)) -	(SELECT PRODUCT_COST FROM PRODUCTS WHERE PRODUCT_PRICE =
				(SELECT MIN(PRODUCT_PRICE)FROM PRODUCTS)) AS COST_DIFFERENCE;
				
--16) Which month has the most sales?

SELECT DATE_TRUNC('month', date) AS MONTH,
	COUNT(*) AS SALES_COUNT
FROM SALES
GROUP BY DATE_TRUNC('month', date)
ORDER BY SALES_COUNT DESC
LIMIT 1;
