--1)What is the total budget allocated for all the Harry Potter movies released after 2005?

SELECT SUM(BUDGET) AS TOTAL_BUDGET
FROM MOVIES
WHERE MOVIE_TITLE LIKE 'Harry Potter%'
	AND RELEASE_YEAR > 2005;

--2)Which movie has the longest runtime and profit of it?

SELECT MOVIE_TITLE,
	BOX_OFFICE - BUDGET AS REVENUE
FROM MOVIES
WHERE RUNTIME =
		(SELECT MAX(RUNTIME)
			FROM MOVIES);
--3)List all the characters who belong to Gryffindor house and not totally human.

SELECT CHARACTER_NAME,
	SPECIES
FROM CHARACTERS
WHERE HOUSE = 'Gryffindor'
	AND SPECIES NOT LIKE ('Human');

--4)Which light has the most unique spells?

SELECT LIGHT,
	COUNT(DISTINCT INCANTATION) AS MOST_LIGHTS
FROM SPELLS
WHERE LIGHT IS NOT NULL
GROUP BY LIGHT
ORDER BY MOST_LIGHTS DESC
LIMIT 1;

--5)Which character has the 3rd highest number of dialogues in "Harry Potter and the Order of the Phoenix"?

SELECT C.CHARACTER_NAME,
	COUNT(D.DIALOGUE_ID) AS NUM_DIALOGUES
FROM DIALOGUE D
JOIN CHARACTERS C ON D.CHARACTER_ID = C.CHARACTER_ID
JOIN CHAPTERS CH ON D.CHAPTER_ID = CH.CHAPTER_ID
JOIN MOVIES M ON CH.MOVIE_ID = M.MOVIE_ID
WHERE M.MOVIE_TITLE = 'Harry Potter and the Order of the Phoenix'
GROUP BY C.CHARACTER_NAME
ORDER BY NUM_DIALOGUES DESC
LIMIT 1
OFFSET 2;

--6)What is the total profit generated all movies in the series?

SELECT SUM(BOX_OFFICE - BUDGET) AS TOTAL_PROFIT,
	ROUND(SUM(BOX_OFFICE - BUDGET) * 100.0 / SUM(BOX_OFFICE),
		2) AS PERCENTAGE
FROM MOVIES;

--7)List all the boys who have not been sorted into any house.

SELECT CHARACTER_NAME
FROM CHARACTERS
WHERE HOUSE IS NULL
	AND GENDER = 'Male';

--8)Which movie has the highest ratio of box office revenue to budget?

SELECT MOVIE_TITLE,
	BOX_OFFICE - BUDGET AS PROFIT
FROM MOVIES
ORDER BY PROFIT DESC
LIMIT 1;

--9)For each movie, list the top 3 characters who have the highest number of dialogues, along with the number of dialogues spoken by each character.

SELECT MOVIE_TITLE,
	CHARACTER_NAME,
	NUM_DIALOGUES
FROM
	(SELECT M.MOVIE_TITLE,
			C.CHARACTER_NAME,
			COUNT(D.DIALOGUE_ID) AS NUM_DIALOGUES,
			ROW_NUMBER() OVER (PARTITION BY M.MOVIE_TITLE ORDER BY COUNT(D.DIALOGUE_ID) DESC) AS RN
		FROM MOVIES M
		JOIN CHAPTERS CH ON M.MOVIE_ID = CH.MOVIE_ID
		JOIN DIALOGUE D ON CH.CHAPTER_ID = D.CHAPTER_ID
		JOIN CHARACTERS C ON D.CHARACTER_ID = C.CHARACTER_ID
		GROUP BY M.MOVIE_TITLE,
			C.CHARACTER_NAME) AS RANKED
WHERE RN <= 3;

--10)For each house, find the average runtime of the movies in which characters belonging to that house have appeared, along with the house name.

SELECT C.HOUSE,
	ROUND(AVG(M.RUNTIME),2) AS AVERAGE_RUNTIME
FROM CHARACTERS C
JOIN DIALOGUE D ON C.CHARACTER_ID = D.CHARACTER_ID
JOIN CHAPTERS CH ON D.CHAPTER_ID = CH.CHAPTER_ID
JOIN MOVIES M ON CH.MOVIE_ID = M.MOVIE_ID
WHERE C.HOUSE IS NOT NULL
GROUP BY C.HOUSE
ORDER BY AVERAGE_RUNTIME DESC;

--11)List all the movies along with the names of the characters who have dialogues spoken in places 
--categorized as "School", sorted by movie title and character name.EXCEPT the 3 lead roles.

SELECT DISTINCT M.MOVIE_TITLE,
	C.CHARACTER_NAME
FROM MOVIES M
JOIN CHAPTERS CH ON M.MOVIE_ID = CH.MOVIE_ID
JOIN DIALOGUE D ON CH.CHAPTER_ID = D.CHAPTER_ID
JOIN CHARACTERS C ON D.CHARACTER_ID = C.CHARACTER_ID
JOIN PLACES P ON D.PLACE_ID = P.PLACE_ID
WHERE P.PLACE_CATEGORY = 'Hogwarts'
	AND C.CHARACTER_NAME NOT IN ('Harry Potter','Ron Weasley','Hermione Granger')
ORDER BY M.MOVIE_TITLE,
	C.CHARACTER_NAME;

--12)For each movie, find the total number of unique places where dialogues were spoken, along with the movie title.

SELECT M.MOVIE_TITLE,
	COUNT(DISTINCT P.PLACE_ID) AS UNIQUE_PLACES_COUNT
FROM MOVIES M
JOIN CHAPTERS CH ON M.MOVIE_ID = CH.MOVIE_ID
JOIN DIALOGUE D ON CH.CHAPTER_ID = D.CHAPTER_ID
JOIN PLACES P ON D.PLACE_ID = P.PLACE_ID
GROUP BY M.MOVIE_TITLE;

--13)List the top 3 characters who have spoken the most dialogues in the 'Harry Potter and the Goblet of Fire' movie, 
--along with the number of dialogues spoken by each character.EXCEPT the 3 lead characters.

WITH GOBLET_OF_FIRE_DIALOGUES AS
	(SELECT C.CHARACTER_NAME,
			COUNT(*) AS NUM_DIALOGUES
		FROM DIALOGUE D
		JOIN CHAPTERS CH ON D.CHAPTER_ID = CH.CHAPTER_ID
		JOIN CHARACTERS C ON D.CHARACTER_ID = C.CHARACTER_ID
		JOIN MOVIES M ON CH.MOVIE_ID = M.MOVIE_ID
		WHERE M.MOVIE_TITLE = 'Harry Potter and the Goblet of Fire'
			AND C.CHARACTER_NAME NOT IN ('Harry Potter','Ron Weasley','Hermione Granger')
		GROUP BY C.CHARACTER_NAME)
SELECT CHARACTER_NAME,
	NUM_DIALOGUES
FROM GOBLET_OF_FIRE_DIALOGUES
ORDER BY NUM_DIALOGUES DESC
LIMIT 3;

--14)List the top 5 characters who have spoken the most dialogues across all Harry Potter movies, excluding the characters Harry Potter, Ron Weasley, and Hermione Granger. Include the total number of dialogues spoken by each character.

WITH CHARACTER_DIALOGUES AS
	(SELECT C.CHARACTER_NAME,
			COUNT(*) AS NUM_DIALOGUES
		FROM DIALOGUE D
		JOIN CHARACTERS C ON D.CHARACTER_ID = C.CHARACTER_ID
		WHERE C.CHARACTER_NAME NOT IN ('Harry Potter','Ron Weasley','Hermione Granger')
		GROUP BY C.CHARACTER_NAME)
SELECT CHARACTER_NAME,
	NUM_DIALOGUES
FROM CHARACTER_DIALOGUES
ORDER BY NUM_DIALOGUES DESC
LIMIT 5;

--15)List all the movies along with the names of the top 3 characters who have spoken the most dialogues in each movie, excluding the characters Harry Potter, Ron Weasley, and Hermione Granger. Include the number of dialogues spoken by each character.

WITH MOVIE_CHARACTERS_DIALOGUES AS
	(SELECT M.MOVIE_ID,
			M.MOVIE_TITLE,
			C.CHARACTER_NAME,
			COUNT(*) AS NUM_DIALOGUES
		FROM DIALOGUE D
		JOIN CHAPTERS CH ON D.CHAPTER_ID = CH.CHAPTER_ID
		JOIN CHARACTERS C ON D.CHARACTER_ID = C.CHARACTER_ID
		JOIN MOVIES M ON CH.MOVIE_ID = M.MOVIE_ID
		WHERE C.CHARACTER_NAME NOT IN ('Harry Potter','Ron Weasley','Hermione Granger')
		GROUP BY M.MOVIE_ID,
			M.MOVIE_TITLE,
			C.CHARACTER_NAME),
	RANKED_DIALOGUES AS
	(SELECT MOVIE_ID,
			MOVIE_TITLE,
			CHARACTER_NAME,
			NUM_DIALOGUES,
			ROW_NUMBER() OVER (PARTITION BY MOVIE_ID ORDER BY NUM_DIALOGUES DESC) AS RN
		FROM MOVIE_CHARACTERS_DIALOGUES)
SELECT MOVIE_TITLE,
	CHARACTER_NAME,
	NUM_DIALOGUES
FROM RANKED_DIALOGUES
WHERE RN <= 3
ORDER BY MOVIE_ID, RN;

--16)Show the amount of inhuman characters.
SELECT SPECIES,
	COUNT(CHARACTER_NAME)
FROM CHARACTERS
WHERE SPECIES IS NOT NULL
	AND SPECIES != 'Human'
GROUP BY SPECIES
ORDER BY COUNT DESC

--17)Which movie has the most non human characters ?

WITH NON_HUMAN_CHARACTERS_PER_MOVIE AS
	(SELECT M.MOVIE_TITLE,
			COUNT(DISTINCT C.CHARACTER_ID) AS NUM_NON_HUMAN_CHARACTERS
		FROM MOVIES M
		JOIN CHAPTERS CH ON M.MOVIE_ID = CH.MOVIE_ID
		JOIN DIALOGUE D ON CH.CHAPTER_ID = D.CHAPTER_ID
		JOIN CHARACTERS C ON D.CHARACTER_ID = C.CHARACTER_ID
		WHERE C.SPECIES != 'Human'
		GROUP BY M.MOVIE_TITLE)
SELECT MOVIE_TITLE,
	NUM_NON_HUMAN_CHARACTERS
FROM NON_HUMAN_CHARACTERS_PER_MOVIE
ORDER BY NUM_NON_HUMAN_CHARACTERS DESC
LIMIT 1;

--18)Which movie has the most unique places where dialogues were spoken?

WITH UNIQUE_PLACES_PER_MOVIE AS
	(SELECT M.MOVIE_TITLE,
			COUNT(DISTINCT P.PLACE_ID) AS NUM_UNIQUE_PLACES
		FROM MOVIES M
		JOIN CHAPTERS CH ON M.MOVIE_ID = CH.MOVIE_ID
		JOIN DIALOGUE D ON CH.CHAPTER_ID = D.CHAPTER_ID
		JOIN PLACES P ON D.PLACE_ID = P.PLACE_ID
		GROUP BY M.MOVIE_TITLE)
SELECT MOVIE_TITLE,
	NUM_UNIQUE_PLACES
FROM UNIQUE_PLACES_PER_MOVIE
ORDER BY NUM_UNIQUE_PLACES DESC
LIMIT 1;

--19)What is the most popular location in each film?

WITH DIALOGUE_COUNTS_PER_MOVIE AS
	(SELECT M.MOVIE_TITLE,
			P.PLACE_NAME,
			COUNT(*) AS DIALOGUE_COUNT
		FROM MOVIES M
		JOIN CHAPTERS CH ON M.MOVIE_ID = CH.MOVIE_ID
		JOIN DIALOGUE D ON CH.CHAPTER_ID = D.CHAPTER_ID
		JOIN PLACES P ON D.PLACE_ID = P.PLACE_ID
		GROUP BY M.MOVIE_TITLE,
			P.PLACE_NAME),
	MAX_DIALOGUE_COUNT_PER_MOVIE AS
	(SELECT MOVIE_TITLE,
			MAX(DIALOGUE_COUNT) AS MAX_DIALOGUE_COUNT
		FROM DIALOGUE_COUNTS_PER_MOVIE
		GROUP BY MOVIE_TITLE)
SELECT D.MOVIE_TITLE,
	D.PLACE_NAME,
	D.DIALOGUE_COUNT
FROM DIALOGUE_COUNTS_PER_MOVIE D
JOIN MAX_DIALOGUE_COUNT_PER_MOVIE M ON D.MOVIE_TITLE = M.MOVIE_TITLE
AND D.DIALOGUE_COUNT = M.MAX_DIALOGUE_COUNT
ORDER BY D.MOVIE_TITLE;

